.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 hufeng <hufeng@uniontech.com>,
.\"
.TH "deepin-deb-installer" "1" "2021-1-28" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-deb-installer \- package manager for deepin.
.SH SYNOPSIS
deepin-deb-installer [FILE(s)...] [OPTIONS...]
.SH DESCRIPTION
Package Installer helps users install and remove local packages.
.PP
Package Installer is an easy-to-use .deb package management tool with a simple interface for users to quickly install customized applications not included in App Store supporting bulk installation, version identification and auto completion.
.SH OPTIONS
.TP
\fBFILE\fR
Specifies the file to open when
.B deepin-deb-installer
starts. If this is not specified,
.B deepin-deb-installer
will load file choose page. Multiple files can be loaded if they are
separated by spaces.
.PP
-h  --help 
       Prints the command line options.
.PP
-v  --version
       Output version information and exit.
.PP

.SH SEE ALSO
https://github.com/linuxdeepin/deepin-deb-installer
.SH AUTHOR
.PP
.B deepin-deb-installer
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT cuizhen@\:uniontech.com
Cuizhen
.ME
for the Debian Project (but may be used by others)

