.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 hufeng <hufeng@uniontech.com>,
.\"
.TH "deepin-deb-installer-dependsInstall" "1" "2021-1-28" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-deb-installer-dependsInstall \- install wine application for deepin-deb-installer.
.SH SYNOPSIS
deepin-deb-installer-dependsInstall
.SH DESCRIPTION
Install wine depends for deepin-deb-installer
.PP

.SH SEE ALSO
https://github.com/linuxdeepin/deepin-deb-installer
.SH AUTHOR
.PP
.B deepin-deb-installer-dependsInstall
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT cuizhen@\:uniontech.com
Cuizhen
.ME
for the Debian Project (but may be used by others)

